version: '1.0'
services:
  pycount-frontend:
    image: pycount-frontend:dev
    container_name: pycount-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
      -
