name: CI/CD

on: push

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      # gitversion/execute step omitted for brevity
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '6.x'
          includePrerelease: true
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }}
          tags: |
            duratm/pycount-frontend:latest
            duratm/pycount-frontend:${{ env.SEMVER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-manifests:
    name: Update Manifests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yq
        uses: mikefarah/yq@v4
      - name: Update manifests
        run: |
          yq eval -i '.spec.template.spec.containers[0].image = "duratm/pycount-frontend:${{ needs.calculate-version.outputs.semVer }}"' kubernetes/pycount-frontend-deploy.yaml
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "duratmathias@gmail.com"
          git add .
          git commit -m "Update manifests to version ${{ needs.build.outputs.semVer }}"
          git push
